### ISSUE TITLE
Fejl ved upload af data fra plugin, når database type er GeoPackage

### ISSUE THREAD

**Issue by bvthomsen** [AestasGIS/QGIS-DMP-Plugin-installation#20]
Efter gennemført opdatering af feature i DMP plugin og i forbindelse med opdatering af de lokale lag fejler plugin med følgende meddelelse

```
Der opstod en fejl ved udførelse af Python-kode: 

KeyError: 'omr-navn' 
Traceback (most recent call last):
  File "C:\Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\dmp_manager\dmp_manager.py", line 330, in 
    commitAction.triggered.connect(lambda:self.rightClickAction('commit', crawler))
  File "C:\Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\dmp_manager\dmp_manager.py", line 436, in rightClickAction
    self.updDMP(pkid, crawler, connection, tblCur, tblRef, pkName, pkQuote, tCode)
  File "C:\Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\dmp_manager\dmp_manager.py", line 650, in updDMP
    updateLayers (curl,refl, result, pkName, pkQuote, pkid)
  File "C:\Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\dmp_manager\helper.py", line 676, in updateLayers
    f.setAttribute(k2, v2)
KeyError: 'omr-navn'


Python-version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-version: 3.22.10-Białowieża Białowieża, 6a63fd37 
Efter gennemført upload af rettelser til DMP, kommer følgende fejlmeddelese fra plugin

Pythonsti:
C:/PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python
C:/Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.10\bin\python39.zip
C:\PROGRA~1\QGIS32~1.10\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib
C:\Program Files\QGIS 3.22.10\bin
C:\PROGRA~1\QGIS32~1.10\apps\Python39
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Bo Victor Thomsen/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```
Fejlen kommer *kun*, når der bruges GeoPackage som lokal database, og skyldes brug af en bestemt metode "loadVectorTableFromConnection" i objekt "QgsAbstractDatabaseProviderConnection"
Fejlrettelse er i gang.

**Comment by bvthomsen** [comment]
rettet
